/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import entity.CreditCard;
import entity.User;
import util.DBHelper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 *
 * @author Edwin Malek
 */
public class CreditCardManager {

    private DBHelper db;

    public CreditCardManager() throws Exception {
        this.db = new DBHelper();
    }

    /**
     * public int createCreditCard(CreditCardInfo info){ try { String sql =
     * "insert into credit_card(number, expiration_date, security_code,
     * name_on_card, type)" +"values('" + info.number.toString() + "','" +
     * info.expiration_date.toString() +"','" + info.security_code.toString() +
     * "','" + info.name_on_card.toString() + "','" + info.card_type+"')";
     *
     * return this.db.executeSQL(sql).get(0); } catch (SQLException ex) { return
     * -1; } }
     */
    public int createCreditCard(CreditCard info) {
        try {
//        	 String sql = "SELECT * from creditcards WHERE number = "+info.getNumber()+" and expiration_date ="+info.getExpiration_date()+
//        			 " and security_code = "+info.getSecurity_code()+" and userid = " + info.getUser_id() + " limit 1";
        	 String sql = "SELECT * from creditcards WHERE userids = " + info.getUser_id() + " limit 1";
             ResultSet rs = this.db.getSQLResult(sql);
             while (rs.next()) {
                 return -1;
             }
           sql = "insert into creditcards(number, expiration_date, "
                    + "security_code, name_on_card, type, userids, address)"
                    + "values('" + info.getNumber() + "', '" + info.getExpiration_date()
                    + "','" + info.getSecurity_code() + "','" + info.getName_on_card() + "', '" + info.getCard_type()
                    + "' ,'" + info.getUser_id() + "','"+ info.getFulladdress() +"')";

            return this.db.executeSQL(sql).get(0);// this is ID generated by the DB
        } catch (SQLException ex) {
            return -1;
        }
    }

    public CreditCard getCreditCard(int userID) throws Exception {
        try {
            CreditCard card = null;
            String sql = "SELECT * from credit_card WHERE userId = " + userID;
            ResultSet rs = this.db.getSQLResult(sql);
            while (rs.next()) {
                card = new CreditCard();
//                card.card_type = rs.getString("type");
//                card.number = rs.getString("number");
//                card.name_on_card = rs.getString("name_on_card");
//                card.expiration_date = rs.getString("expiration_date");
//                card.security_code = rs.getString("security_code");
//                card.user_id = rs.getInt("userId");
                
                card.setCard_type(rs.getString("type"));
                card.setNumber(rs.getString("number"));
                card.setName_on_card(rs.getString("name_on_card"));
                card.setExpiration_date(rs.getString("expiration_date"));
                card.setSecurity_code(rs.getString("security_code"));
                card.setUser_id(rs.getInt("userId"));
                
                
            }

            this.db.executeSQL(sql);// this is ID generated by the DB
            return card;
        } catch (Exception e) {
            throw e;
        }
    }
    
    public int countCreditCard(int userID){
      try{
            int count=0;
            String sql = "SELECT COUNT(*) as count_card from credit_card WHERE userId = " + userID;
            ResultSet rs = this.db.getSQLResult(sql);
             while (rs.next()) {
                 count = rs.getInt("count_card");
             }
            return count;
        
    }catch (SQLException ex) {
            return -1;
        }
    }
    
    public void updateCard(CreditCard info) throws SQLException {

        try {
            String sql = "UPDATE creditcards SET  number = '" + info.getNumber() + "', expiration_date = '"
                    + info.getExpiration_date() +  "', security_code = '"+ info.getSecurity_code()+ "', name_on_card ='"+info.getName_on_card()+"', type = '"+info.getCard_type()+"' WHERE userids = " + info.getUser_id();

            this.db.executeSQL(sql);
        } catch (SQLException ex) {
            throw ex;
        }
    }
    

}
